flyway.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
flyway.user=${POSTGRES_ADMIN_USER}
flyway.password=${POSTGRES_ADMIN_PASSWORD}
flyway.schemas=core
flyway.locations=filesystem:src/main/resources/db/migration,filesystem:src/main/resources/db/seed
