server:
  servlet:
    session:
      timeout: 120s
spring:
  application:
    name: wtow-transfer
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_SERVICE_USER}
    password: ${POSTGRES_SERVICE_PASSWORD}
  jpa.properties.hibernate.default_schema: core
